const PayrollActionTypes = {
    FETCH_PAYROLL: 'FETCH_PAYROLL',
    FETCH_PAYROLL_PENDING: 'FETCH_PAYROLL_PENDING',
    FETCH_PAYROLL_FULFILLED: 'FETCH_PAYROLL_FULFILLED',
    UPLOAD_PAYROLL: 'UPLOAD_PAYROLL',
    UPLOAD_PAYROLL_PENDING: 'UPLOAD_PAYROLL_PENDING',
    UPLOAD_PAYROLL_FULFILLED: 'UPLOAD_PAYROLL_FULFILLED',
};


export {
    PayrollActionTypes
}